### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by aoyawale**
just a starting point.

### CODE REVIEW

**Review by codrcodz — CHANGES_REQUESTED** [review]
- git clone dev-ranger and use that as your dev env
- place group vars in ansible-playbooks/group_vars/osp-rbac
- populate meta/main.yml
- populate README.md with example group and host vars
- ensure node-specific variables are in host_vars
- mv gitignore .gitignore
- nest variables inside of an "osp_rbac" dictionary; see ceph-admin's "devices" dictionary or teaming's "team" dictionary as an example
- setup a sample group/host_vars file that is populated with example domains, projects, groups, and users for testing

Note: I setup an inventory and playbook for osp-rbac.

**Comment by aoyawale** [comment]
after I complete this. do I just submit commits from the repos the dev-ranger creates or seperate ones?

**Comment by codrcodz** [comment]
dev-ranger is designed to give us a consistent dev env so we all working on the same python, ansible, and shade library versions. But as long as your 'pip freeze' output is the same for your system and virtualenv, it doesn't matter.

**Comment by codrcodz** [comment]
Closing this PR in favor of PR #3 . See PR #3 as an example of how to do the other OSP-related roles.

**Pull request closed without merging**
